// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace HomeComfort.ML.Model
{
    public class ComfortModelInput
    {
        [ColumnName("OutdoorTemp"), LoadColumn(0)]
        public float OutdoorTemp { get; set; }


        [ColumnName("IndoorTemp"), LoadColumn(1)]
        public float IndoorTemp { get; set; }


        [ColumnName("IndoorHumidity"), LoadColumn(2)]
        public float IndoorHumidity { get; set; }


        [ColumnName("TimeOfDay"), LoadColumn(3)]
        public float TimeOfDay { get; set; }


        [ColumnName("TurnOnAC"), LoadColumn(4)]
        public string TurnOnAC { get; set; }


        [ColumnName("TurnOnHeat"), LoadColumn(5)]
        public float TurnOnHeat { get; set; }


    }
}
