// This file was auto-generated by ML.NET Model Builder. 

using System;
using Microsoft.ML.Data;

namespace HomeComfort.ML.Model
{
    public class HeatModelOutput
    {
        public float Score { get; set; }
    }
}
