// This file was auto-generated by ML.NET Model Builder. 

using System;
using System.IO;
using Microsoft.ML;

namespace HomeComfort.ML.Model
{
    public class HeatConsumeModel
    {
        private static Lazy<PredictionEngine<ComfortModelInput, HeatModelOutput>> PredictionEngine = new Lazy<PredictionEngine<ComfortModelInput, HeatModelOutput>>(CreatePredictionEngine);

        public static string MLNetModelPath = Path.GetFullPath("HeatMLModel.zip");

        // For more info on consuming ML.NET models, visit https://aka.ms/mlnet-consume
        // Method for consuming model in your app
        public static HeatModelOutput Predict(ComfortModelInput input)
        {
            HeatModelOutput result = PredictionEngine.Value.Predict(input);
            return result;
        }

        public static PredictionEngine<ComfortModelInput, HeatModelOutput> CreatePredictionEngine()
        {
            // Create new MLContext
            MLContext mlContext = new MLContext();

            // Load model & create prediction engine
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ComfortModelInput, HeatModelOutput>(mlModel);

            return predEngine;
        }
    }
}
